services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/ask  # Utilisation du nom du service backend comme URL

  backend:
    build: ./backend
    ports:
      - "8000:8000"
